db.url=jdbc:postgresql://ep-muddy-darkness-alt7l54m-pooler.c-3.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_yDNW25ICKdQb&sslmode=require&channel_binding=require
client.secret=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
secret.key=very_secret_key_not_to_share